### ISSUE TITLE
Error if pet status starts with a small letter

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/petstore-component-nodejs#24]
While following the instruction given in our online documentation https://docs.elastic.io/getting-started/webhooks-flow.html, we encountered problem if the pet status is given in small letter. This was not an issue in the previous version of the component.

Here is input JSON:
```
{
  "petname": "Gromit",
  "petstatus": "sold"
}
```
Here is the mapping stage:

<img width="985" alt="Screenshot 2021-01-08 at 10 42 49" src="https://user-images.githubusercontent.com/11753582/104000262-489f1580-519e-11eb-9558-06dbf6101ea7.png">

Here is the result with an error:

```
Starting your Docker container ...
Starting application in apprunner...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Will try to start app at /home/apprunner
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
invokeModuleFunction – init is not found
Checking if incoming messages is lightweight...
Checking if incoming messages is lightweight...
Empty headers so not lightweight.
Message processed, going to emit
About to process message...
Error: Status is required
    at TaskExec.process (/home/apprunner/lib/actions/createPet.js:42:11)
    at /home/apprunner/node_modules/elasticio-sailor-nodejs/lib/executor.js:33:62
    at new Promise (<anonymous>)
    at TaskExec.process (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/executor.js:32:9)
    at /home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:341:22
    at new Promise (<anonymous>)
    at Sailor.runExec (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:317:15)
    at Sailor.processMessage (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:661:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Sailor.processMessageAndMaybeShutdownCallback (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:194:20)
    at async readAndProcess (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/amqp.js:238:21)
    at async Promise.all (index 0)
    at async Amqp.listenQueue (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/amqp.js:249:9)
    at async putOutToSea (/home/apprunner/node_modules/elasticio-sailor-nodejs/run.js:33:5)
    at async run (/home/apprunner/node_modules/elasticio-sailor-nodejs/run.js:78:9)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
[INFO  tini (1)] Spawned child process '/run.sh' with pid '6'
Starting application in apprunner...
Will try to start app at /home/apprunner
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
invokeModuleFunction – init is not found
Checking if incoming messages is lightweight...
Empty headers so not lightweight.
Checking if incoming messages is lightweight...
Error occurred during trigger or action processing
Checking if incoming messages is lightweight...
```

The error is gone if you use the petstatus in capital letter like `Sold`.

**Comment by khanzadyan** [comment]
Most likely the recent update of dependencies caused this problem. This could be a significant problem since we are using the example in our onboarding and getting started flows and we expect our new customers to follow the example and have a successful experience. @jhorbulyk

**Comment by jhorbulyk** [comment]
If you look into the allowed values for statuses, you can see that the allowed values all start with capital letters.

![Screenshot from 2021-01-08 14-04-29](https://user-images.githubusercontent.com/5710732/104018646-73976280-51ba-11eb-97b6-853ca17834fb.png)

I suppose the error message could be tweaked slightly to say **Provided status is invalid.** Would this resolve your concern @khanzadyan ?

(This behavior appears to have been present in the code for the last 15 months.)

**Comment by jhorbulyk** [comment]
Or should I broaden the behavior of the component to be case insensitive?

**Comment by khanzadyan** [comment]
I'm a bit concerned this change was there for all this time and nobody has noticed it. When the documentation was written, we used all small letters and it worked. It works with the previous version of the component. With the new version there is this discrepancy.

I suppose the documentation can be changed to include only capital letters. This means we need to re-created several screenshots. My problem is that we have backwards incompatibility.

**Comment by jhorbulyk** [comment]
I can also change the component to be case insensitive...
